export const paths = {
  landing: '/',
  privacyPolicy: '/privacy-policy',
  employee: {
    root: '/employee',
    dashboard: '/employee/dashboard',
    profile: '/employee/profile',
    leaderboard: '/employee/leaderboard',
    orders: '/employee/orders',
    products: '/employee/products',
    salesReport: '/employee/sales-report',
    messages: '/employee/messages',
    settings: '/employee/settings',
  },
  superAdmin: {
    root: '/super-admin',
    dashboard: '/super-admin/dashboard',
    profile: '/super-admin/profile',
    leaderboard: '/super-admin/leaderboard',
    orders: '/super-admin/orders',
    products: '/super-admin/products',
    salesReport: '/super-admin/sales-report',
    messages: '/super-admin/messages',
    settings: '/super-admin/settings',
  },
  auth: {
    root: '/auth',
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
} as const;
